import { z } from "zod";

const text = z.string();
const liste = z.array(text);
const karte = z.object({ titel: text, text: text });
const faqEintrag = z.object({ frage: text, antwort: text });

export const siteSchema = z.object({
  marke: z.object({
    name: text,
    domain: z.url({ message: "marke.domain muss eine vollständige Adresse sein, z. B. https://www.example.de" }),
    email: text,
    telefon: text,
    ort: text,
    region: text,
    einsatzgebiet: liste,
  }),
  service: z.object({
    start_uhr: z.number().int().min(0).max(24),
    ende_uhr: z.number().int().min(0).max(24),
    antwortzeit_minuten: z.number().positive(),
    antwort_frist: text,
  }),
  preise: z.object({
    pro_buchung: z.number().nonnegative(),
    test_tage: z.number().int().positive(),
    gruenderpreis: z.object({
      pro_buchung: z.number().nonnegative(),
      monate: z.number().int().positive(),
      plaetze_gesamt: z.number().int().positive(),
      plaetze_frei: z.number().int().min(0).nullable().optional(),
      erinnerung_vorher: text,
    }),
  }),
  lead_magnet: z.object({ check_stunden: z.number().positive(), verbesserungen: z.number().int().positive() }),
  links: z.object({ buchungslink: text, buchungsanbieter: text }),
  formular: z.object({ anbieter: z.enum(["netlify", "extern"]), endpunkt: text, name: text }),
  analytics: z.object({ plausible: z.boolean(), plausible_domain: text }),
  seo: z.object({ titel: text, beschreibung: text }),
  navigation: z.array(z.object({ text: text, ziel: text })),
  cta: z.object({ test: text, test_kurz: text, check: text, check_kurz: text }),
  hero: z.object({ kicker: text.optional(), titel: text, unterzeile: text, vertrauen: liste }),
  laufband: z.object({ punkte: liste.min(1) }),
  chat_demo: z.object({
    uhrzeit: text.optional(),
    notiz: text.optional(),
    beschreibung: text,
    geprueft: text,
    nachrichten: z
      .array(z.object({ von: z.enum(["gast", "wir"]), absender: text.optional(), text: text }))
      .min(2)
      .max(6)
      .refine((liste) => liste.some((n) => n.von === "wir"), { message: "Mindestens eine Nachricht muss von uns sein" }),
  }),
  problem: z.object({
    kicker: text.optional(), titel: text, karten: z.array(karte) }),
  rechner: z.object({
    titel: text,
    intro: text,
    start_objekte: z.number(),
    start_buchungen: z.number(),
    start_buchungswert: z.number(),
    start_anteil: z.number(),
    label_objekte: text,
    label_buchungen: text,
    label_buchungswert: text,
    label_anteil: text,
    ergebnis_verlust: text,
    ergebnis_kosten: text,
    hinweis: text,
    cta: text,
  }),
  gaestereise: z.object({
    kicker: text.optional(),
    titel: text,
    text: text,
    phasen: z.array(z.object({ titel: text, punkte: liste })),
  }),
  ablauf: z.object({
    kicker: text.optional(), titel: text, schritte: z.array(karte.extend({ hinweis: text.optional() })) }),
  leistungen: z.object({
    kicker: text.optional(), titel: text, karten: z.array(karte) }),
  vergleich: z.object({
    kicker: text.optional(),
    titel: text,
    intro: text,
    beschriftung: text,
    label_sie: text,
    label_wir: text,
    zusammenfassung: text,
    leer: text,
    cta: text,
    cta_hinweis: text,
    zeilen: z.array(z.object({ aufgabe: text, wer: z.enum(["sie", "wir"]) })).min(1),
  }),
  ergebnisse: z.object({
    titel: text,
    kennzahlen: z.array(z.object({ wert: text, beschreibung: text, quelle: text })).nullish().transform((v) => v ?? []),
    stimmen: z
      .array(z.object({ zitat: text, name: text, ort: text.optional(), objekte: text.optional(), beispiel: z.boolean().optional() }))
      .nullish()
      .transform((v) => v ?? []),
  }),
  persoenlich: z.object({
    sichtbar: z.boolean(),
    kicker: text.optional(),
    titel: text,
    einleitung: text,
    themen: liste,
    themen_hinweis: text.optional(),
    text: liste,
    unterschrift: text,
    rolle: text,
    foto: text,
    foto_alt: text,
    foto_platzhalter: text,
  }),
  preise_abschnitt: z.object({
    kicker: text.optional(),
    titel: text,
    einheit: text,
    test_hinweis: text,
    rechner_frage: text,
    rechner_start: z.number().int().positive(),
    rechner_max: z.number().int().positive(),
    rechner_einheit: text,
    rechner_zeitraum: text,
    punkte: liste,
    abrechnung_booking: text,
    steuer: text,
    buchung_definition: text,
    gruenderpreis_titel: text,
    gruenderpreis_text: text,
    zaehler_text: text,
    zaehler_hinweis: text,
    bedingungen_aufklappen: text,
    test_titel: text,
    test_bedingungen: z.array(karte),
    gp_titel: text,
    gp_bedingungen: liste,
  }),
  angebote: z.object({
    titel: text,
    karten: z
      .array(
        z.object({
          etikett: text,
          titel: text,
          preis: text,
          anliegen: z.enum(["test", "check", "agentur"]),
          stil: z.enum(["hell", "dunkel"]),
          empfohlen: z.boolean().optional(),
          punkte: liste,
          cta: text,
        }),
      )
      .min(1),
  }),
  anfrage: z.object({
    kicker: text.optional(),
    untertitel: text.optional(),
    gruss: text.optional(),
    titel: text,
    anliegen_frage: text,
    anliegen: z.object({ test: text, check: text, agentur: text }),
    schritt: text,
    frage_objekte: text,
    objekte: liste,
    frage_plattformen: text,
    plattformen: liste,
    label_region: text,
    frage_problem: text,
    probleme: liste,
    label_problem_text: text,
    frage_kontakt: text,
    label_name: text,
    label_email: text,
    label_telefon: text,
    label_inserat: text,
    label_wunschpaket: text,
    wunschpaket_aendern: text,
    hinweis_inserat_check: text,
    weiter: text,
    zurueck: text,
    absenden: text,
    senden_laeuft: text,
    datenschutz: text,
    datenschutz_link: text,
    fehler_auswahl: text,
    fehler_plattform: text,
    fehler_name: text,
    fehler_email: text,
    fehler_url: text,
    fehler_senden: text,
  }),
  faq: z.object({
    kicker: text.optional(),
    titel: text,
    sichtbar: z.number().int().positive().optional(),
    weitere: text.optional(),
    fragen: z.array(faqEintrag).min(1),
  }),
  abschluss: z.object({ kicker: text.optional(), titel: text, text: text }),
  footer: z.object({ hinweis_marken: text }),
  inserats_check: z.object({
    seo_titel: text,
    seo_beschreibung: text,
    titel: text,
    unterzeile: text,
    was_titel: text,
    was_punkte: liste,
    was_hinweis: text,
    nutzen: z.array(karte),
    formular_titel: text,
    faq: z.array(faqEintrag),
  }),
  steckbrief: z.object({
    seo_titel: text,
    kicker: text.optional(),
    titel: text,
    einleitung: text,
    sicherheit: text,
    pdf_hinweis: text,
    pdf_link: text,
    absenden: text,
    abschnitte: z
      .array(
        z.object({
          titel: text,
          felder: z
            .array(
              z
                .object({
                  name: z.string().regex(/^[a-z0-9_]+$/, "Feldname: nur Kleinbuchstaben, Zahlen und Unterstriche"),
                  label: text,
                  typ: z.enum(["text", "email", "tel", "textarea", "auswahl", "mehrfach"]),
                  pflicht: z.boolean().optional(),
                  platzhalter: text.optional(),
                  optionen: liste.optional(),
                })
                .refine((f) => !["auswahl", "mehrfach"].includes(f.typ) || (f.optionen?.length ?? 0) > 0, {
                  message: "Felder vom Typ auswahl oder mehrfach brauchen optionen",
                }),
            )
            .min(1),
        }),
      )
      .min(1),
  }),
  infomappe: z.object({
    datei: z.string().regex(/^[a-z0-9-]+\.pdf$/),
    titel: text,
    untertitel: text,
    einleitung: text,
    leistungen_titel: text,
    ablauf_titel: text,
    preis_titel: text,
    preis_zeile: text,
    steckbrief_titel: text,
    steckbrief_einleitung: text,
    online_titel: text,
    online_text: text,
    rueckweg_text: text,
    abschluss_text: text,
    kontakt_titel: text,
    email_betreff: text,
    email_text: text,
  }),
  danke: z.object({
    titel: text,
    text_allgemein: text,
    text_check: text,
    text_test: text,
    text_agentur: text,
    text_steckbrief: text,
    steckbrief_titel: text.optional(),
    steckbrief_text: text.optional(),
    steckbrief_button: text.optional(),
    naechster_titel: text,
    naechster_text: text,
    termin_button: text,
    termin_hinweis: text,
    zurueck: text,
  }),
  impressum: z.object({
    name: text,
    firmenzusatz: text,
    strasse: text,
    plz_ort: text,
    land: text,
    telefon: text,
    email: text,
    ust_id: text,
    wirtschafts_id: text,
    verantwortlich_inhalt: text,
  }),
  datenschutz: z.object({ stand: text, speicherdauer_anfragen: text, aufsichtsbehoerde: text }),
});

export const regionSchema = z.object({
  name: text,
  im_satz: text,
  seo_titel: text,
  seo_beschreibung: text,
  titel: text,
  unterzeile: text,
  einleitung_titel: text,
  einleitung: text,
  partner_titel: text,
  partner_text: text,
  einsatzgebiet: liste,
});

export type Site = z.infer<typeof siteSchema>;
export type Region = z.infer<typeof regionSchema> & { slug: string };
